name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    steps:

    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 9.x

    - name: Setup NuGet cache
      uses: actions/cache@v4.1.2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.props') }}
        restore-keys: ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore ./smart-id-net-client.sln
    
    - name: Test
      run: dotnet test --no-build ./smart-id-net-client.sln
